### PR TITLE
Adds Persistent History, cleaner initialization.

### PR DESCRIPTION
**Pull request by DoctorBud**
- Adds persistent history capability (~/.noctua_repl_history).
- Delays startup of readline until other initialization occurs, so that the prompt line isn't dirtied with initialization logging.

### CODE REVIEW

**Comment by kltm** [comment]
I appreciate the fixes and will merge. I would prefer a bit more discussion however--my direction to fix this was to explore vorpal.

**Comment by DoctorBud** [comment]
Agreed that discussion is appropriate. When I initially started it, I thought it would be a 5-minute one-liner and could be deleted later in favor of a better solution. It turned out to be a one-hour, 50-line effort, but is still throw-away-able. I'll try to more communicative.

**Comment by kltm** [comment]
I'm just jealous that you got to it before I had an excuse to play with vorpal a bit more ;)

**Comment by cmungall** [comment]
playing with vorpals sounds dangerous

**Pull request merged**
